In [1]:

import pandas as pd
python
import pandas as pd
print(pd.__version__)

NameError: name 'python' is not defined

In [2]:
import pandas as pd
print(pd.__version__)

3.0.3

In [3]:
import panda as pd

customers = pd.read_csv("customer.csv")

ModuleNotFoundError: No module named 'panda'

In [4]:
import pandas as pd

customers = pd.read_csv("customer.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'customer.csv'

In [5]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\TomJ6\Downloads\Workshop 8\wk8.final
['.ipynb_checkpoints', 'Untitled.ipynb', 'wk8-customers.csv', 'wk8-inventory.csv', 'wk8-products.csv', 'wk8-sales.csv', 'wk8-stores.csv']

In [6]:
customers.head()

NameError: name 'customers' is not defined

In [7]:
import pandas as pd

customers.head()

NameError: name 'customers' is not defined

In [8]:
import pandas as pd

customers = pd.read_csv('wk8-customers.cvs')

FileNotFoundError: [Errno 2] No such file or directory: 'wk8-customers.cvs'

In [9]:
import os

print('Current folder')
print(os.getcwd())

print('\nfiles:')
for file in os.listdir():
    print(repr(file))

Current folder
C:\Users\TomJ6\Downloads\Workshop 8\wk8.final

files:
'.ipynb_checkpoints'
'Untitled.ipynb'
'wk8-customers.csv'
'wk8-inventory.csv'
'wk8-products.csv'
'wk8-sales.csv'
'wk8-stores.csv'

In [10]:
import pandas as pd

customers = pd.read_csv("wk8-customers.csv")

customers.head()

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,3/15/2021
1,2,Mary,Johnson,NaN,212.555.6789,456 Park Ave,New York,NY,10022,11/2/2020
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,California,90001-1234,5/20/2021
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,NaN
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,9/12/2020

In [11]:
customers.head()

products.head()

stores.head()

sales.head()

inventory.head()

NameError: name 'products' is not defined

In [12]:
import pandas as pd

customers = pd.read_csv("wk8-customers.csv")
products = pd.read_csv("wk8-products.csv")
stores = pd.read_csv("wk8-stores.csv")
sales = pd.read_csv("wk8-sales.csv")
inventory = pd.read_csv("wk8-inventory.csv")

In [13]:
customers.head()
products.head()
stores.head()
sales.head()
inventory.head()

,inventory_id,store_id,product_id,quantity_in_stock,last_restock_date,reorder_level
0,1,1,1,25,10/15/2022,10.0
1,2,1,5,42,11/2/2022,15.0
2,3,1,10,18,9/30/2022,8.0
3,4,1,15,5,10/20/2022,10.0
4,5,1,20,12,NaN,15.0